config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  devise_for :users

  root to: 'apps/posts#index'

  scope module: :apps do
    resources :posts do
      resources :comments, only: [:index, :new, :create]
    end

    resource :profile, only: [:show] do
      resource :avatar, only: [:update]
    end

    resources :accounts, only: [:show] do
      resources :followers, only: [:index]
      resources :followings, only: [:index]
      resources :account_posts, only: [:index]
    end
  end

  namespace :api, defaults: { format: :json } do
    scope '/posts/:post_id' do
      resource :like, only: [:show, :create, :destroy]
    end

    scope '/accounts/:account_id' do
      resources :follows, only: [:create]
      resources :unfollows, only: [:create]
    end
  end

end

app/views/commons/_dropdown.html.haml
.header_right
  - if user_signed_in?
    .dropdown
      = image_tag current_user.avatar_image, class: 'dropbtn'
      .dropdown-content
        = link_to 'Home', root_path
        = link_to 'My Profile', profile_path
        = link_to 'Logout', destroy_user_session_path, data: { turbo_method: 'delete' }
  - else
    = link_to 'Login', new_user_session_path, class: 'loginBtn'

app/views/commons/_follow.html.haml
.container
  .header_row
    .header_left
      = link_to :back do
        = image_tag 'back.png', class: 'header_back'
    .header_center #{title}
    .header_right
      = render 'commons/dropdown'

  .users
    - users.each do |user|
      .user
        = link_to account_path(user) do
          .user_meta
            .user_icon
              = image_tag user.avatar_image
            .user_name
              = user.account

app/views/commons/_images.html.haml
- case post.images.count
- when 1
  .post_images.one
    .image-first
      = image_tag post.images[0]
- when 2
  .post_images.two
    .image-first
      = image_tag post.images[0]
    .image-second
      = image_tag post.images[1]
- when 3
  .post_images.three
    .image-first
      = image_tag post.images[0]
    .image-second
      = image_tag post.images[1]
    .image-third
      = image_tag post.images[2]
- when 4
  .post_images.four
    = image_tag post.images[0]
    = image_tag post.images[1]
    = image_tag post.images[2]
    = image_tag post.images[3]

app/views/commons/_posts.html.haml
.container
  .header_row
    .header_left
      = link_to new_post_path do
        %i.fa-regular.fa-camera
    .header_right
      = render 'commons/dropdown'

  .posts
    - posts.each do |post|
      .post.js-post{ id: "post-#{post.id}", data: { post_id: post.id} }
        .post_meta
          .post_icon
            = link_to account_path(post.user) do
              = image_tag post.user.avatar_image
          .post_info
            .post_author_upper
              = post.user.account
            .post_time-ago
              = post.time_ago_display

        = render 'commons/images', post: post

        .post_actions
          .post_like.hidden.active-heart
            = image_tag 'heart-active.svg'
          .post_like.hidden.inactive-heart
            = image_tag 'heart.svg'
          .post_comment
            = link_to post_comments_path(post) do
              = image_tag 'comment.png'
          .post_share
            - share_url = polymorphic_url(post, host: request.base_url)
            = link_to "https://twitter.com/share?#{ {url: share_url}.to_query }", target: '_blank' do
              = image_tag 'share.png'
        .post_liked-by
          = post.display_like_count
        .post_text
          .post_author_lower
            = post.user.account
          .post_content
            = post.content

app/views/commons/_profile.html.haml
.profilePage_user_data
  .profilePage_user_content
    .profilePage_user_data_count
      = @user.posts.count
    .profilePage_user_data_label
      Posts
  .profilePage_user_content
    = link_to account_followers_path(@user) do
      .profilePage_user_data_count#followers-count
        = @user.followers.count
      .profilePage_user_data_label
        Followers
  .profilePage_user_content
    = link_to account_followings_path(@user) do
      .profilePage_user_data_count
        = @user.followings.count
      .profilePage_user_data_label
        Following

.profilePage_user_posts
  - @posts.each do |post|
    .profilePage_user_post
      = link_to account_account_posts_path(@user, anchor: "post-#{post.id}") do
        = render 'commons/images', post: post